/// theme.dart
///
/// Design tokens and ThemeData for the Vault app.
///
/// REFERENCE: Google's open-source "Now in Android" app
/// (github.com/android/nowinandroid, Apache-2.0) — its `core/designsystem`
/// module is the canonical Material 3 implementation on Android. This file
/// ports its principles to Flutter rather than copying Compose code:
///
///  * Colour comes from Material 3 TONAL ROLES, not hand-picked hex. The roles
///    below were generated by Flutter's own material_color_utilities from the
///    Vault brand green (#22C55E): the primary tone from the `fidelity`
///    variant (keeps the brand's live-state green), containers and neutrals
///    from `tonalSpot` — the same split NiA's green "Android" scheme uses
///    (bright Green80 primary, Green30 container, green-gray neutrals).
///  * Typography is NiA's scale (Type.kt): Material 3 sizes with bold titles.
///  * Navigation follows NiaNavigationDefaults: primaryContainer indicator,
///    onPrimaryContainer for the selected item, onSurfaceVariant otherwise,
///    filled icon when selected and outlined when not.
///  * Cards are filled tonal surfaces (surfaceContainer*), not outlined boxes;
///    hierarchy comes from tone and type, borders are reserved for inputs and
///    secondary buttons.
///
/// Semantics are unchanged from the previous palette: green is reserved for
/// live / verified state, amber for caution, red for failure, and nothing is
/// ever communicated by colour alone.
///
/// Contrast (WCAG, against the page background #101510): onSurface 15.5:1,
/// onSurfaceVariant 11.2:1, outline 5.9:1 — every text role clears 4.5:1.

library;

import 'package:flutter/material.dart';

abstract final class VaultColors {
  // --- Material 3 neutral roles (tonalSpot, seed #22C55E) ------------------
  /// Page background (M3 `surface`).
  static const background = Color(0xFF101510);

  /// Default card / panel fill (M3 `surfaceContainerLow`).
  static const surface = Color(0xFF181D18);

  /// Raised element inside a card: inputs, tiles, code (M3 `surfaceContainerHigh`).
  static const surfaceHigh = Color(0xFF262B26);

  /// Highest tonal step: selected tiles, tracks (M3 `surfaceContainerHighest`).
  static const surfaceHighest = Color(0xFF313630);

  /// Navigation bar fill (M3 `surfaceContainer`).
  static const surfaceContainer = Color(0xFF1C211C);

  /// Hairlines and dividers (M3 `outlineVariant`).
  static const border = Color(0xFF414941);

  /// Input and outlined-button borders (M3 `outline`).
  static const borderStrong = Color(0xFF8B9389);

  /// Primary text (M3 `onSurface`).
  static const foreground = Color(0xFFE0E4DC);

  /// Secondary text (M3 `onSurfaceVariant`).
  static const muted = Color(0xFFC1C9BE);

  /// Tertiary text, captions, disabled-looking meta (M3 `outline`, 5.9:1).
  static const faint = Color(0xFF8B9389);

  // --- Brand / semantic ----------------------------------------------------
  /// Live, verified, primary action (fidelity primary).
  static const accent = Color(0xFF4BE277);
  static const onAccent = Color(0xFF003915);

  /// Tonal container for selected / positive state (tonalSpot primaryContainer).
  static const accentDim = Color(0xFF1B5129);
  static const onAccentDim = Color(0xFFB6F1BB);

  /// Informational (tonalSpot tertiary — teal, harmonised with the seed).
  static const info = Color(0xFFA1CED7);
  static const infoContainer = Color(0xFF1F4D55);

  /// Caution: built but unproven, needs attention.
  static const warn = Color(0xFFF5C26B);
  static const warnContainer = Color(0xFF4A3A12);

  /// Failure (M3 error roles).
  static const danger = Color(0xFFFFB4AB);
  static const dangerContainer = Color(0xFF93000A);
  static const onDangerContainer = Color(0xFFFFDAD6);

  // --- Telemetry series (CVD-separable; each also has its own stroke) -----
  static const cpu = Color(0xFF7DD3FC); // sky
  static const gpu = Color(0xFFFBBF24); // amber
  static const npu = Color(0xFFC4B5FD); // violet
  static const duty = accent; // green
}

abstract final class VaultSpace {
  /// 4 dp grid. Section rhythm is 16 / 24 / 32.
  static const xs = 4.0;
  static const sm = 8.0;
  static const md = 12.0;
  static const lg = 16.0;
  static const xl = 24.0;
  static const xxl = 32.0;

  /// M3 shape scale: large (cards) 16, medium (tiles, inputs) 12, small 8.
  static const radius = 16.0;
  static const radiusMd = 12.0;
  static const radiusSm = 8.0;

  /// Android minimum touch target.
  static const touch = 48.0;
}

abstract final class VaultText {
  /// Numbers that update in place (latency, %, MB) are tabular so digits
  /// don't jitter the layout as they change.
  static const mono = TextStyle(
    fontFamily: 'monospace',
    fontFeatures: [FontFeature.tabularFigures()],
  );
}

/// NiA Type.kt, verbatim sizes / line heights / tracking / weights.
TextTheme _niaTextTheme(Color onSurface, Color onSurfaceVariant) {
  TextStyle s(double size, double line, double tracking, FontWeight weight,
          [Color? color]) =>
      TextStyle(
        fontSize: size,
        height: line / size,
        letterSpacing: tracking,
        fontWeight: weight,
        color: color ?? onSurface,
      );
  return TextTheme(
    displayLarge: s(57, 64, -0.25, FontWeight.w400),
    displayMedium: s(45, 52, 0, FontWeight.w400),
    displaySmall: s(36, 44, 0, FontWeight.w400),
    headlineLarge: s(32, 40, 0, FontWeight.w400),
    headlineMedium: s(28, 36, 0, FontWeight.w400),
    headlineSmall: s(24, 32, 0, FontWeight.w400),
    titleLarge: s(22, 28, 0, FontWeight.w700),
    titleMedium: s(18, 24, 0.1, FontWeight.w700),
    titleSmall: s(14, 20, 0.1, FontWeight.w500),
    bodyLarge: s(16, 24, 0.5, FontWeight.w400),
    bodyMedium: s(14, 20, 0.25, FontWeight.w400),
    bodySmall: s(12, 16, 0.4, FontWeight.w400, onSurfaceVariant),
    labelLarge: s(14, 20, 0.1, FontWeight.w500),
    labelMedium: s(12, 16, 0.5, FontWeight.w500),
    labelSmall: s(11, 16, 0.5, FontWeight.w500),
  );
}

ThemeData buildVaultTheme() {
  const scheme = ColorScheme(
    brightness: Brightness.dark,
    primary: VaultColors.accent,
    onPrimary: VaultColors.onAccent,
    primaryContainer: VaultColors.accentDim,
    onPrimaryContainer: VaultColors.onAccentDim,
    secondary: Color(0xFFB8CCB6),
    onSecondary: Color(0xFF233425),
    secondaryContainer: Color(0xFF394B3A),
    onSecondaryContainer: Color(0xFFD4E8D1),
    tertiary: VaultColors.info,
    onTertiary: Color(0xFF003640),
    tertiaryContainer: VaultColors.infoContainer,
    onTertiaryContainer: Color(0xFFBDEAF3),
    error: VaultColors.danger,
    onError: Color(0xFF690005),
    errorContainer: VaultColors.dangerContainer,
    onErrorContainer: VaultColors.onDangerContainer,
    surface: VaultColors.background,
    onSurface: VaultColors.foreground,
    surfaceDim: VaultColors.background,
    surfaceContainerLowest: Color(0xFF0B0F0B),
    surfaceContainerLow: VaultColors.surface,
    surfaceContainer: VaultColors.surfaceContainer,
    surfaceContainerHigh: VaultColors.surfaceHigh,
    surfaceContainerHighest: VaultColors.surfaceHighest,
    onSurfaceVariant: VaultColors.muted,
    outline: VaultColors.borderStrong,
    outlineVariant: VaultColors.border,
    inverseSurface: VaultColors.foreground,
    onInverseSurface: Color(0xFF2D322C),
    inversePrimary: Color(0xFF006D36),
  );
  // Merged onto the platform base so every style carries the Roboto family
  // and geometry; component themes (buttons, app bar) use these directly.
  final text = Typography.material2021(platform: TargetPlatform.android)
      .white
      .merge(_niaTextTheme(scheme.onSurface, scheme.onSurfaceVariant));
  final pill = RoundedRectangleBorder(borderRadius: BorderRadius.circular(100));

  return ThemeData(
    useMaterial3: true,
    brightness: Brightness.dark,
    colorScheme: scheme,
    textTheme: text,
    scaffoldBackgroundColor: scheme.surface,
    dividerColor: scheme.outlineVariant,
    visualDensity: VisualDensity.standard,
    materialTapTargetSize: MaterialTapTargetSize.padded,
    appBarTheme: AppBarTheme(
      backgroundColor: scheme.surface,
      surfaceTintColor: Colors.transparent,
      scrolledUnderElevation: 0,
      elevation: 0,
      centerTitle: false,
      titleSpacing: VaultSpace.lg,
      titleTextStyle: text.titleLarge,
    ),
    cardTheme: CardThemeData(
      color: scheme.surfaceContainerLow,
      surfaceTintColor: Colors.transparent,
      elevation: 0,
      margin: EdgeInsets.zero,
      clipBehavior: Clip.antiAlias,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(VaultSpace.radius),
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: scheme.surfaceContainerHigh,
      hintStyle: text.bodyLarge!.copyWith(color: scheme.outline),
      labelStyle: text.bodyMedium!.copyWith(color: scheme.onSurfaceVariant),
      floatingLabelStyle: text.bodySmall!.copyWith(color: scheme.primary),
      prefixIconColor: scheme.onSurfaceVariant,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(VaultSpace.radiusMd),
        borderSide: BorderSide.none,
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(VaultSpace.radiusMd),
        borderSide: BorderSide.none,
      ),
      disabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(VaultSpace.radiusMd),
        borderSide: BorderSide.none,
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(VaultSpace.radiusMd),
        borderSide: BorderSide(color: scheme.primary, width: 2),
      ),
      contentPadding: const EdgeInsets.symmetric(
        horizontal: VaultSpace.lg,
        vertical: 14,
      ),
    ),
    filledButtonTheme: FilledButtonThemeData(
      style: FilledButton.styleFrom(
        minimumSize: const Size(0, VaultSpace.touch),
        padding: const EdgeInsets.symmetric(horizontal: VaultSpace.xl),
        shape: pill,
        textStyle: text.labelLarge,
        disabledBackgroundColor: scheme.onSurface.withValues(alpha: 0.12),
        disabledForegroundColor: scheme.onSurface.withValues(alpha: 0.38),
      ),
    ),
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        minimumSize: const Size(0, VaultSpace.touch),
        padding: const EdgeInsets.symmetric(horizontal: VaultSpace.xl),
        foregroundColor: scheme.onSurface,
        textStyle: text.labelLarge,
        shape: pill,
      ).copyWith(
        side: WidgetStateProperty.resolveWith((states) => BorderSide(
              // NiaButtonDefaults: 1 dp outline, 12 % onSurface when disabled.
              color: states.contains(WidgetState.disabled)
                  ? scheme.onSurface.withValues(alpha: 0.12)
                  : scheme.outline,
            )),
      ),
    ),
    textButtonTheme: TextButtonThemeData(
      style: TextButton.styleFrom(
        minimumSize: const Size(0, VaultSpace.touch),
        foregroundColor: scheme.primary,
        textStyle: text.labelLarge,
        shape: pill,
      ),
    ),
    iconButtonTheme: IconButtonThemeData(
      style: IconButton.styleFrom(
        minimumSize: const Size(VaultSpace.touch, VaultSpace.touch),
        foregroundColor: scheme.onSurfaceVariant,
      ),
    ),
    switchTheme: SwitchThemeData(
      trackOutlineColor: WidgetStateProperty.resolveWith((states) =>
          states.contains(WidgetState.selected) ? Colors.transparent : scheme.outline),
    ),
    checkboxTheme: CheckboxThemeData(
      side: BorderSide(color: scheme.onSurfaceVariant, width: 2),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
    ),
    segmentedButtonTheme: SegmentedButtonThemeData(
      style: SegmentedButton.styleFrom(
        minimumSize: const Size(0, VaultSpace.touch),
        selectedBackgroundColor: scheme.secondaryContainer,
        selectedForegroundColor: scheme.onSecondaryContainer,
        foregroundColor: scheme.onSurface,
        side: BorderSide(color: scheme.outline),
        textStyle: text.labelLarge,
      ),
    ),
    progressIndicatorTheme: ProgressIndicatorThemeData(
      color: scheme.primary,
      linearTrackColor: scheme.surfaceContainerHighest,
      circularTrackColor: Colors.transparent,
      linearMinHeight: 4,
    ),
    dividerTheme: DividerThemeData(
      color: scheme.outlineVariant,
      thickness: 1,
      space: 1,
    ),
    listTileTheme: ListTileThemeData(
      titleTextStyle: text.bodyLarge,
      subtitleTextStyle: text.bodyMedium!.copyWith(color: scheme.onSurfaceVariant),
      iconColor: scheme.onSurfaceVariant,
      contentPadding: EdgeInsets.zero,
      minVerticalPadding: VaultSpace.sm,
    ),
    dialogTheme: DialogThemeData(
      backgroundColor: scheme.surfaceContainerHigh,
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(28)),
      titleTextStyle: text.headlineSmall,
      contentTextStyle: text.bodyMedium!.copyWith(color: scheme.onSurfaceVariant),
    ),
    tooltipTheme: TooltipThemeData(
      decoration: BoxDecoration(
        color: scheme.inverseSurface,
        borderRadius: BorderRadius.circular(VaultSpace.xs),
      ),
      textStyle: text.bodySmall!.copyWith(color: scheme.onInverseSurface),
    ),
    navigationBarTheme: NavigationBarThemeData(
      backgroundColor: scheme.surfaceContainer,
      surfaceTintColor: Colors.transparent,
      elevation: 0,
      height: 80,
      // NiaNavigationDefaults.
      indicatorColor: scheme.primaryContainer,
      labelBehavior: NavigationDestinationLabelBehavior.alwaysShow,
      labelTextStyle: WidgetStateProperty.resolveWith(
        (states) => text.labelMedium!.copyWith(
          color: states.contains(WidgetState.selected)
              ? scheme.onSurface
              : scheme.onSurfaceVariant,
          fontWeight: states.contains(WidgetState.selected)
              ? FontWeight.w700
              : FontWeight.w500,
        ),
      ),
      iconTheme: WidgetStateProperty.resolveWith(
        (states) => IconThemeData(
          size: 24,
          color: states.contains(WidgetState.selected)
              ? scheme.onPrimaryContainer
              : scheme.onSurfaceVariant,
        ),
      ),
    ),
    snackBarTheme: SnackBarThemeData(
      backgroundColor: scheme.inverseSurface,
      contentTextStyle: text.bodyMedium!.copyWith(color: scheme.onInverseSurface),
      actionTextColor: scheme.inversePrimary,
      behavior: SnackBarBehavior.floating,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(VaultSpace.xs)),
    ),
  );
}
