package com.example.vault_rag_test

import android.content.Context
import android.content.pm.PackageManager
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import android.util.Log
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import java.security.KeyFactory
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PrivateKey
import java.security.SecureRandom
import java.security.Signature
import java.security.spec.ECGenParameterSpec
import java.util.concurrent.Executors
import javax.crypto.BadPaddingException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * AndroidKeyStore, exposed to Dart as `vault/keystore`.
 *
 * TWO KEYS, NEITHER EXPORTABLE
 *
 *  - `vault_tee_aes_master`  AES-256-GCM, encrypt/decrypt. Protects chunk
 *    content at rest in vault.db.
 *  - `vault_tee_attestation` EC P-256, sign, SHA-256 digest. Signs the
 *    canonical bytes of every context capsule.
 *
 * Both are generated in StrongBox when the device has one and accepts the
 * spec, and in the TEE-backed KeyStore otherwise. [keyStatus] reports what
 * KeyInfo *says* the key lives in afterwards — this class never infers
 * "hardware" from the SoC name, and it never falls back to a key held in app
 * memory. If AndroidKeyStore itself is unusable every call fails with
 * KEYSTORE_ERROR and the Dart side fails closed.
 *
 * AES-GCM WIRE FORMAT: `IV(12) || ciphertext || tag(16)`.
 *
 * The IV is generated by the keystore, not by this class. AndroidKeyStore
 * keys default to `randomizedEncryptionRequired = true`, which makes the
 * keystore refuse caller-chosen IVs for encryption — precisely so that an
 * app bug cannot reuse one. We read `cipher.iv` back after init, check it is
 * 12 bytes, and prepend it.
 *
 * WHY STRONGBOX IS NOT FREE: StrongBox is a separate secure element on a
 * slow bus. Per-operation latency is tens to hundreds of milliseconds, versus
 * low milliseconds in the TEE. Query-time cost stays bounded because only
 * the top-K winners are ever decrypted ([decryptBatch], one channel hop), but
 * ingest pays one keystore operation per chunk.
 *
 * THREADING: keystore calls are binder IPC into keystore2 and may block, so
 * they run on one worker thread (same pattern as [LlamaChannel]); results
 * are posted back to the main thread as MethodChannel requires.
 *
 * LOGGING: error categories only. Never plaintext, ciphertext, or keys.
 */
class KeystoreChannel(
    messenger: BinaryMessenger,
    private val context: Context,
) : MethodChannel.MethodCallHandler {

    companion object {
        private const val TAG = "VaultKeystore"
        private const val CHANNEL = "vault/keystore"
        private const val PROVIDER = "AndroidKeyStore"
        const val AES_ALIAS = "vault_tee_aes_master"
        const val SIGNING_ALIAS = "vault_tee_attestation"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val IV_LENGTH = 12
        private const val TAG_BITS = 128
        private const val TAG_LENGTH = TAG_BITS / 8

        // Bound into the signing key's attestation certificate. A fixed
        // challenge proves nothing about freshness; the chain is still
        // evidence of where the key was generated and what it may do.
        private val ATTESTATION_CHALLENGE =
            "vault-capsule-signing-key/v1".toByteArray(Charsets.UTF_8)
    }

    private val channel = MethodChannel(messenger, CHANNEL).apply {
        setMethodCallHandler(this@KeystoreChannel)
    }
    private val worker = Executors.newSingleThreadExecutor { r ->
        Thread(r, "vault-keystore").apply { isDaemon = true }
    }
    private val main = Handler(Looper.getMainLooper())
    private val random = SecureRandom()

    private class ChannelError(val code: String, message: String) : Exception(message)

    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        val op: (() -> Any)? = when (call.method) {
            "encrypt" -> { { encrypt(bytesArg(call)) } }
            "decrypt" -> { { decrypt(bytesArg(call)) } }
            "decryptBatch" -> { { listArg(call).map { decrypt(it) } } }
            "signPayload" -> { { signPayload(bytesArg(call)) } }
            "getPublicKey" -> { { publicKey() } }
            "getAttestationChain" -> { { attestationChain() } }
            "keyStatus" -> { { keyStatus() } }
            "isEnclaveActive" -> { { isEnclaveActive() } }
            "sessionSeal" -> { { sessionSeal(call) } }
            "sessionOpen" -> { { sessionOpen(call) } }
            else -> null
        }
        if (op == null) {
            result.notImplemented()
            return
        }
        worker.execute {
            try {
                val value = op()
                main.post { result.success(value) }
            } catch (e: ChannelError) {
                Log.w(TAG, "${call.method} failed: ${e.code}")
                main.post { result.error(e.code, e.message, null) }
            } catch (e: Throwable) {
                // Class name only: keystore exception messages can include
                // key parameters, and nothing here should echo input bytes.
                Log.w(TAG, "${call.method} failed: ${e.javaClass.simpleName}")
                main.post {
                    result.error("KEYSTORE_ERROR", e.javaClass.simpleName, null)
                }
            }
        }
    }

    fun dispose() {
        channel.setMethodCallHandler(null)
        worker.shutdown()
    }

    // ------------------------------------------------------------------ AES

    private fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, aesKey())
        val iv = cipher.iv
        if (iv == null || iv.size != IV_LENGTH) {
            throw ChannelError("KEYSTORE_ERROR", "Unexpected IV length")
        }
        val sealed = cipher.doFinal(plaintext) // ciphertext || 16-byte tag
        return iv + sealed
    }

    private fun decrypt(payload: ByteArray): ByteArray {
        if (payload.size < IV_LENGTH + TAG_LENGTH) {
            throw ChannelError("MALFORMED", "Payload shorter than IV + tag")
        }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            aesKey(),
            GCMParameterSpec(TAG_BITS, payload, 0, IV_LENGTH),
        )
        return try {
            cipher.doFinal(payload, IV_LENGTH, payload.size - IV_LENGTH)
        } catch (e: BadPaddingException) {
            // AEADBadTagException is a BadPaddingException. Nothing
            // unauthenticated is ever returned: doFinal releases no output
            // when the tag check fails.
            throw ChannelError("AUTH_FAILED", "GCM authentication failed")
        }
    }

    @Synchronized
    private fun aesKey(): SecretKey {
        val ks = keyStore()
        (ks.getKey(AES_ALIAS, null) as? SecretKey)?.let { return it }

        fun spec(strongBox: Boolean): KeyGenParameterSpec {
            val b = KeyGenParameterSpec.Builder(
                AES_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setKeySize(256)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setRandomizedEncryptionRequired(true)
            if (strongBox && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                b.setIsStrongBoxBacked(true)
            }
            return b.build()
        }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        return withStrongBoxFallback("AES") { strongBox ->
            generator.init(spec(strongBox))
            generator.generateKey()
        }
    }

    // ---------------------------------------------------------------- ECDSA

    private fun signPayload(payload: ByteArray): ByteArray {
        // SHA256withECDSA over the canonical capsule bytes. The Dart side
        // hashes the same bytes separately to publish canonical_digest; the
        // signature is NOT over that digest, so nothing is hashed twice.
        val signer = Signature.getInstance("SHA256withECDSA")
        signer.initSign(signingKey())
        signer.update(payload)
        return signer.sign() // ASN.1 DER (r, s)
    }

    private fun publicKey(): ByteArray {
        signingKey() // ensure it exists
        // X.509 SubjectPublicKeyInfo DER. The private half never leaves.
        return keyStore().getCertificate(SIGNING_ALIAS).publicKey.encoded
    }

    private fun attestationChain(): List<ByteArray> {
        signingKey()
        return keyStore().getCertificateChain(SIGNING_ALIAS)?.map { it.encoded }
            ?: emptyList()
    }

    @Synchronized
    private fun signingKey(): PrivateKey {
        val ks = keyStore()
        (ks.getKey(SIGNING_ALIAS, null) as? PrivateKey)?.let { return it }

        fun spec(strongBox: Boolean, attest: Boolean): KeyGenParameterSpec {
            val b = KeyGenParameterSpec.Builder(SIGNING_ALIAS, KeyProperties.PURPOSE_SIGN)
                .setAlgorithmParameterSpec(ECGenParameterSpec("secp256r1"))
                .setDigests(KeyProperties.DIGEST_SHA256)
            if (attest) b.setAttestationChallenge(ATTESTATION_CHALLENGE)
            if (strongBox && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                b.setIsStrongBoxBacked(true)
            }
            return b.build()
        }

        val generator = KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, PROVIDER)
        return try {
            withStrongBoxFallback("EC") { strongBox ->
                generator.initialize(spec(strongBox, attest = true))
                generator.generateKeyPair().private
            }
        } catch (e: Exception) {
            // Some keymaster implementations reject attestation outright.
            // The key is still hardware-generated; it just has no chain.
            Log.w(TAG, "EC attestation unavailable: ${e.javaClass.simpleName}")
            withStrongBoxFallback("EC(no-attest)") { strongBox ->
                generator.initialize(spec(strongBox, attest = false))
                generator.generateKeyPair().private
            }
        }
    }

    /** Tries StrongBox, then the default (TEE) keystore. Never software-in-app. */
    private fun <T> withStrongBoxFallback(label: String, generate: (Boolean) -> T): T {
        if (hasStrongBox()) {
            try {
                return generate(true)
            } catch (e: Exception) {
                val expected = Build.VERSION.SDK_INT >= Build.VERSION_CODES.P &&
                    e is StrongBoxUnavailableException
                Log.i(TAG, "$label: StrongBox rejected (${e.javaClass.simpleName}" +
                    "${if (expected) "" else ", unexpected"}); using TEE KeyStore")
            }
        }
        return generate(false)
    }

    // --------------------------------------------------------------- status

    private fun hasStrongBox(): Boolean =
        Build.VERSION.SDK_INT >= Build.VERSION_CODES.P &&
            context.packageManager.hasSystemFeature(PackageManager.FEATURE_STRONGBOX_KEYSTORE)

    private fun keyStatus(): Map<String, Any> {
        val aesLevel = securityLevel(
            SecretKeyFactory.getInstance(aesKey().algorithm, PROVIDER)
                .getKeySpec(aesKey(), KeyInfo::class.java) as KeyInfo,
        )
        val signing = signingKey()
        val signingLevel = securityLevel(
            KeyFactory.getInstance(signing.algorithm, PROVIDER)
                .getKeySpec(signing, KeyInfo::class.java),
        )
        return mapOf(
            "keystoreAvailable" to true,
            "aesLevel" to aesLevel,
            "signingLevel" to signingLevel,
            "strongBoxFeature" to hasStrongBox(),
            "sdkInt" to Build.VERSION.SDK_INT,
        )
    }

    private fun securityLevel(info: KeyInfo): String {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            return when (info.securityLevel) {
                KeyProperties.SECURITY_LEVEL_STRONGBOX -> "strongbox"
                KeyProperties.SECURITY_LEVEL_TRUSTED_ENVIRONMENT -> "tee"
                KeyProperties.SECURITY_LEVEL_SOFTWARE -> "software"
                else -> "unknown"
            }
        }
        // Pre-S can only say "secure hardware or not" — reported as tee,
        // never upgraded to strongbox on a guess.
        @Suppress("DEPRECATION")
        return if (info.isInsideSecureHardware) "tee" else "software"
    }

    private fun isEnclaveActive(): Boolean = try {
        val status = keyStatus()
        val hw = setOf("tee", "strongbox")
        status["aesLevel"] in hw && status["signingLevel"] in hw
    } catch (e: Exception) {
        false
    }

    // ------------------------------------------------------ VaultLink session

    private fun sessionSeal(call: MethodCall): ByteArray {
        val key = sessionKey(call)
        val iv = ByteArray(IV_LENGTH).also { random.nextBytes(it) }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key, GCMParameterSpec(TAG_BITS, iv))
        cipher.updateAAD(call.argument<ByteArray>("aad") ?: ByteArray(0))
        return iv + cipher.doFinal(
            call.argument<ByteArray>("plaintext")
                ?: throw ChannelError("BAD_ARGS", "plaintext missing"),
        )
    }

    private fun sessionOpen(call: MethodCall): ByteArray {
        val key = sessionKey(call)
        val payload = call.argument<ByteArray>("payload")
            ?: throw ChannelError("BAD_ARGS", "payload missing")
        if (payload.size < IV_LENGTH + TAG_LENGTH) {
            throw ChannelError("MALFORMED", "Payload shorter than IV + tag")
        }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_BITS, payload, 0, IV_LENGTH))
        cipher.updateAAD(call.argument<ByteArray>("aad") ?: ByteArray(0))
        return try {
            cipher.doFinal(payload, IV_LENGTH, payload.size - IV_LENGTH)
        } catch (e: BadPaddingException) {
            throw ChannelError("AUTH_FAILED", "GCM authentication failed")
        }
    }

    private fun sessionKey(call: MethodCall): SecretKeySpec {
        val raw = call.argument<ByteArray>("key")
        if (raw == null || raw.size != 32) {
            throw ChannelError("BAD_ARGS", "Session key must be 32 bytes")
        }
        return SecretKeySpec(raw, "AES")
    }

    // -------------------------------------------------------------- helpers

    private fun keyStore(): KeyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }

    private fun bytesArg(call: MethodCall): ByteArray =
        call.arguments as? ByteArray ?: throw ChannelError("BAD_ARGS", "Expected bytes")

    private fun listArg(call: MethodCall): List<ByteArray> =
        (call.arguments as? List<*>)?.map {
            it as? ByteArray ?: throw ChannelError("BAD_ARGS", "Expected list of bytes")
        } ?: throw ChannelError("BAD_ARGS", "Expected list of bytes")
}
